### ISSUE TITLE
ThreadSafeActionHandlerIft is NOT lock-free

### ISSUE THREAD

**Issue by pellared** [sbracaloni/thread-safe-action#5]
The description says:

>Why deal with locks when you can have a lock free implementation.

This is not true. Because channels are using locks internally.
Reference:
- https://golang.org/src/runtime/chan.go
- https://stackoverflow.com/questions/13102874/is-gos-buffered-channel-lockless

There is an issue to make channels lock-free, but I do not think it is a priority:
- https://github.com/golang/go/issues/8899

**Comment by sbracaloni** [comment]
Hi @pellared !

You are absolutely right! This library is not lock free. What I meant is more: try to avoid using custom lock/synchronisation when you can use builtin mechanism.
I will change the README to something like:

`Why deal with your own locks when you can use the builtin Golang mechanism`
Thank you :+1:
